### ISSUE TITLE
Issue with Kibana 5.4.0 / Perfect with 7.16.3

### ISSUE THREAD

**Issue by cyberlife-inside** [washim/python-elastic-logstash#3]
Hi washim,

Your wrapper is really easy to use ! Congrats

Nevertheless I am having an issue with Kibana 5.4.0 (currrent production stack) with the following error :
Elastic Search Error: Document mapping type name can't start with '_', found: [_doc]

Nevertheless It works very well with elasticsearch 7.16.3 (my env stack)

Could you tell me how can we adapt the code (or can you adapt it) to make it works well with old Kibana version including 5.4.0 ?

Regards

**Comment by washim** [comment]
Hmm. I can understand. I really don't know what will be the complexity because it was built for 7.x version and not for 5.x. I don't have bandwidth to adopt this but you can try for hack below line inside __init__.py line no 35

`url = self.url + '/' + self.elastic_index + '/_doc/' + str(uuid.uuid1())`
