### ISSUE TITLE
I need more information or how I will reproduce this. Better if you have screenshot of error.

### ISSUE THREAD

**Issue by XDeepZeroX** [washim/python-elastic-logstash#4]
I need more information or how I will reproduce this. Better if you have screenshot of error.

_Originally posted by @washim in https://github.com/washim/python-elastic-logstash/issues/2#issuecomment-877656369_

1. Up elasticsearch in docker container
2. Run app with logger (python-elastic-logstash)
3. Down elasticsearch in docker container

Messages: Unable to connect elastic host. Logstash will restore when available.

Logger slows down

**Comment by washim** [comment]
Its not an issue. Make sure your outbound connection from docker container to Elasticsearch host working fine, if not then you will receive "Unable to connect elastic host. Logstash will restore when available.". This may make your server slow because it is trying to connect continuously internaly and become slow.
